[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "projeto-audio-tcc"
version = "0.1.0"
description = "Pipeline de áudio, espectrograma e detecção simples de acordes"
authors = [{name = "Daniel"}]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=1.24",
    "scipy>=1.11",
    "matplotlib>=3.8",
    "librosa>=0.10.2",
    "soundfile>=0.12"
]